# Generated by Django 5.2 on 2025-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='label', through='task.TaskRelationLabel', through_fields=('task', 'label'), to='label.label', verbose_name='Labels'),
        ),
    ]
