version: "3.9"

services:
    task-manager:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: task-manager
        restart: unless-stopped
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env_prod
        depends_on:
            - db
        command: >
            bash -c "uv run python3 manage.py migrate && uv run python3 manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres
        restart: unless-stopped
        env_file:
            - .env_prod

volumes:
    postgres_data:
