# Generated by Django 5.1.6 on 2025-02-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomStatus',
            new_name='Status',
        ),
    ]
