# Generated by Django 4.2.11 on 2025-02-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nic',
            new_name='nic_name',
        ),
    ]
